# Generated by Django 5.0.6 on 2024-06-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_comment_commentlikesordislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlikesordislikes',
            name='positive',
            field=models.JSONField(default=None),
        ),
    ]
