# Generated by Django 5.0.6 on 2024-06-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_commentlikesordislikes_positive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlikesordislikes',
            name='positive',
        ),
    ]
