# Generated by Django 5.0.6 on 2024-06-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_commentlikesordislikes_positive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='positive',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
