# Generated by Django 5.0.6 on 2024-06-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_comment_positive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='positive',
        ),
        migrations.AddField(
            model_name='comment',
            name='positive_points',
            field=models.TextField(blank=True, null=True),
        ),
    ]
