# Generated by Django 5.0.6 on 2024-06-05 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_comment_positive_comment_positive_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='positive_points',
        ),
        migrations.AlterField(
            model_name='commentlikesordislikes',
            name='content',
            field=models.CharField(choices=[('0', 'liked'), ('1', 'disliked')]),
        ),
        migrations.CreateModel(
            name='NegativePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negative_points', to='product.comment')),
            ],
        ),
        migrations.CreateModel(
            name='PositivePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positive_points', to='product.comment')),
            ],
        ),
    ]
