# Generated by Django 5.0.6 on 2024-06-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_comment_positive_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='product',
            field=models.ManyToManyField(related_name='colors', to='product.product'),
        ),
    ]
