# Generated by Django 5.0.6 on 2024-06-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_productcolor_product_productcolor_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='star',
            new_name='rate',
        ),
    ]
