# Generated by Django 5.0.6 on 2024-06-17 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_star_comment_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlikesordislikes',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_or_dislikes', to='product.comment'),
        ),
        migrations.AlterField(
            model_name='commentlikesordislikes',
            name='content',
            field=models.CharField(choices=[('liked', 'liked'), ('disliked', 'disliked')]),
        ),
        migrations.AlterField(
            model_name='commentlikesordislikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_or_dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
