# Generated by Django 5.0.6 on 2024-05-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='mahdimalvandi6@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
