# Generated by Django 5.0.6 on 2024-06-03 19:39

import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_authenticated'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_authenticated',
        ),
    ]
