# Generated by Django 5.0.6 on 2024-06-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_seen',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
