# Generated by Django 5.0.6 on 2024-06-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
