# Generated by Django 5.0.6 on 2024-06-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_code', '0002_discountcode_is_used_alter_discountcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
